# Before adding this give permissions to ArgoCD to openshift-devspaces
# oc adm policy add-cluster-role-to-user cluster-admin system:serviceaccount:openshift-gitops:openshift-gitops-argocd-application-controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devspaces-install-app
spec:
  project: default
  source:
    repoURL: https://github.com/ozyohthree/devspaces-apps.git
    path: gitops-apps 
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
