apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devworkspace-controller
  namespace: openshift-devspaces # The OpenShift Dev Spaces namespace. The default is openshift-devspaces
  # description: ServiceMonitor for detecting the Dev Workspace Operator metrics Service
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 10s 
      port: metrics
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - openshift-operators
      - openshift-devspaces
  selector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-controller
