apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: che-host
  namespace: openshift-devspaces # Default OpenShift Dev Spaces namespace
  annotations:
    description: ServiceMonitor for detecting the OpenShift Dev Spaces JVM metrics Service.
spec:
  endpoints:
    - interval: 10s 
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - openshift-devspaces # Default OpenShift Dev Spaces namespace
  selector:
    matchLabels:
      app.kubernetes.io/name: devspaces