apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: che-host
  namespace: openshift-devspaces 
spec:
  endpoints:
    - interval: 10s 
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - openshift-devspaces 
  selector:
    matchLabels:
      app.kubernetes.io/name: devspaces