apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: che-app
spec:
  project: default
  source:
    repoURL: https://github.com/ozyohthree/devspaces-apps.git
    path: gitops-config/devspaces 
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
